on: [ push, pull_request ]
name: AIO formatting and linting
jobs:
  format_lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix fmt -- --ci
