# This workflow will build Python packages on every commit.

name: Build nixinstall

on: [ push, pull_request ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build -L
      - uses: actions/upload-artifact@v4
        with:
          name: nixinstall
          path: result/*
